import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MuiProvider from "./_util/client/provider/mui";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "curl",
  description: "Generated by create next app",
};

const CustomProvider = ({ children }: { children: ReactNode }) => {
  return <MuiProvider options={{ key: "mui" }}>{children}</MuiProvider>;
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomProvider>{children}</CustomProvider>
      </body>
    </html>
  );
}
